receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:5555

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  attributes:
    actions:
    - key: environment
      value: testotel
      action: insert

exporters:
  logging:
    #verbosity: detailed
    loglevel: info
  prometheus:
    endpoint: collector:6666
    namespace: default
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus,logging]
    traces:
      receivers: [otlp]
      processors: [batch,attributes]
      exporters: [jaeger,logging,otlp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp,logging]